---

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: Read new kernel version
    command: "cat /home/{{ ansible_user}}/new_kernel_version"
    register: new_kernel_version
  - name: Check running kernel version matches NEW kernel
    assert:
      that: ansible_kernel == new_kernel_version.stdout
      fail_msg: "running kernel {{ ansible_kernel }} differs from specified new kernel {{ new_kernel_version.stdout }}"
      success_msg: "running kernel {{ ansible_kernel }} matches specified new kernel {{ new_kernel_version.stdout }}"
  - name: Get kernel-headers version
    command:
      cmd: "yum list --installed kernel-headers"
      warn: false
    register: yum_kernel_headers
  - name: Check kernel_header package is installed and version matches NEW kernel
    assert:
      that: "yum_kernel_headers.stdout_lines[1].split()[1] in new_kernel_version.stdout"
      fail_msg: "kernel-headers version {{ yum_kernel_headers.stdout_lines[1].split()[1] }} does not match new kernel {{ new_kernel_version.stdout }}"
      success_msg: "kernel-headers version {{ yum_kernel_headers.stdout_lines[1].split()[1] }} matches new kernel {{ new_kernel_version.stdout }}"
