---

- name: Set kernel version
  set_fact:
      kernel_version: "{{ ansible_kernel if kernel_version == 'pinned' else kernel_version }}" # TODO: document fact this gets changed if was "pinned"
- name: Install kernel
  yum:
    name: "{{ kernel_repos[ansible_distribution_version]['packageurl'] }}/kernel-{{ kernel_version }}.rpm"
  register: kernel_install
- name: Install grubby
  yum:
    name: grubby
    state: present
- name: Set specified kernel as default for boot
  grubby:
    version: "{{ kernel_version }}" # TODO document returns?
  register: grubby
- debug:
    msg: "{{ grubby }}"


# name: Disable kernel upgrades
# name: Reboot
# when: kernel_install.changed


- name: Install packages
  yum:
    name: "{{ kernel_repos[ansible_distribution_version]['packageurl'] }}/{{ item }}-{{ kernel_version }}.rpm"
    # name: "kernel-{{ item }}-{{ ansible_kernel }}"
    state: "{{ kernel_pkgs_state }}"
    disable_gpg_check: yes # TODO: fixme
  loop: "{{ kernel_pkgs }}"
