---
- name: Set kernel version
  set_fact:
      kernel_version: "{{ ansible_kernel if kernel_version == 'pinned' else kernel_version }}" # TODO: document fact this gets changed if was "pinned"
- name: Install kernel
  yum:
    name: "{{ kernel_repos[ansible_distribution_version] }}/kernel-{{ kernel_version }}.rpm"
  register: kernel_install
- name: Install grubby
  yum:
    name: grubby
    state: present
- name: Set specified kernel as default for boot
  grubby:
    version: "{{ kernel_version }}" # TODO document returns?
  register: grubby
- name: "read yum.conf"
  ini_read:
    path: /etc/yum.conf
    section: main
  register: yum_conf_main
- set_fact:
    yum_conf_exclude: "{{ yum_conf_main.config.get('exclude', '').split() }}"
- name: Disable upgrades for kernel* in yum.conf
  ini_file:
    path: /etc/yum.conf
    section: main
    option: exclude
    value: "{{ ' '.join((yum_conf_exclude + ([] if 'kernel*' in yum_conf_exclude else ['kernel*']))) }}"
    no_extra_spaces: yes  
- name: Reboot if kernel updated
  reboot:
  when: grubby.changed or ansible_kernel != kernel_version # bit belt-and-braces in case somehow running kernel != default boot
  # TODO: use stackhpc.appliances/reboot_and_wait role here
- name: Install packages
  yum:
    name: "{{ kernel_repos[ansible_distribution_version] }}/{{ item }}-{{ kernel_version }}.rpm"
    # name: "kernel-{{ item }}-{{ ansible_kernel }}"
    state: "{{ kernel_pkgs_state }}"
    disable_gpg_check: yes # TODO: fixme
  loop: "{{ kernel_pkgs }}"
