---

# - name: Install Centos archive repo
#   yum_repository:
#     name: BaseOS-Vault
#     file: CentOS-Base-Vault
#     baseurl: "{{ kernel_repos[ansible_distribution_version]['baseurl'] }}"
#     description: "CentOS-{{ ansible_distribution_version }} - Base Vault (archive)"
#     gpgkey: "{{ kernel_repos[ansible_distribution_version]['gpgkey'] }}"
#     enabled: yes

- name: Set kernel version
  set_fact:
      kernel_version: "{{ ansible_kernel if kernel_version == 'pinned' else kernel_version }}"
- debug:
    msg: "{{ kernel_version }}"
- name: Install kernel
  yum:
    name: "{{ kernel_repos[ansible_distribution_version]['packageurl'] }}/kernel-{{ kernel_version }}.rpm"
- meta: end_play
# name: Install kernel
# name: Install grubby
- name: Set specified kernel as default for boot
  grubby:
    version: "{{ uname.stdout }}"
  register: grubby
- debug:
    msg: "{{ grubby }}"


# name: Disable kernel upgrades
# name: Reboot


- name: Install packages
  yum:
    name: "{{ kernel_repos[ansible_distribution_version]['packageurl'] }}/{{ item }}-{{ kernel_version }}.rpm"
    # name: "kernel-{{ item }}-{{ ansible_kernel }}"
    state: "{{ kernel_pkgs_state }}"
    disable_gpg_check: yes # TODO: fixme
  loop: "{{ kernel_pkgs }}"
