---

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
  - name: Read original kernel version
    command: "cat /home/{{ ansible_user}}/original_kernel_version"
    register: original_kernel_version
    changed_when: false
  - name: Check running kernel version matches ORIGINAL kernel
    assert:
      that: ansible_kernel == original_kernel_version.stdout
      fail_msg: "running kernel {{ ansible_kernel }} differs from original kernel {{ original_kernel_version.stdout }}"
      success_msg: "running kernel {{ ansible_kernel }} matches original kernel {{ original_kernel_version.stdout }}"
